create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  feature_id integer not null,
  reviewer_name text not null,
  review_text text not null,
  rating integer not null check (rating between 1 and 5),
  created_at timestamptz not null default now()
);

alter table public.reviews enable row level security;

drop policy if exists "Anyone can read reviews" on public.reviews;
create policy "Anyone can read reviews"
on public.reviews
for select
to public
using (true);

drop policy if exists "Anyone can add reviews" on public.reviews;
create policy "Anyone can add reviews"
on public.reviews
for insert
to public
with check (
  feature_id between 1 and 11
  and char_length(trim(reviewer_name)) between 1 and 60
  and char_length(trim(review_text)) between 1 and 500
  and rating between 1 and 5
);
